"""update database schema

Revision ID: 573d5a78fc3e
Revises: 
Create Date: 2026-07-11 13:26:42.560843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '573d5a78fc3e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('market_value_rands', sa.BigInteger(), nullable=True))
    op.drop_column('players', 'market_value_rands')
    op.add_column('teams', sa.Column('market_value_rands', sa.BigInteger(), nullable=True))
    op.drop_column('teams', 'market_value_rands')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('market_value_rands', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('teams', 'market_value_rands')
    op.add_column('players', sa.Column('market_value_rands', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('players', 'market_value_rands')
    # ### end Alembic commands ###
