"""UPDATING  table

Revision ID: df00e40e33f8
Revises: fea228ef84fe
Create Date: 2026-07-13 13:09:27.792646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df00e40e33f8'
down_revision: Union[str, Sequence[str], None] = 'fea228ef84fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('is_captain', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('players', sa.Column('saves', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('clean_sheets', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('goals_conceded', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('tackles', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('interceptions', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('clearances', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'clearances')
    op.drop_column('players', 'interceptions')
    op.drop_column('players', 'tackles')
    op.drop_column('players', 'goals_conceded')
    op.drop_column('players', 'clean_sheets')
    op.drop_column('players', 'saves')
    op.drop_column('players', 'is_captain')
    # ### end Alembic commands ###
