"""added 5 new columns in playerstatistics

Revision ID: f9972e204a11
Revises: df00e40e33f8
Create Date: 2026-08-08 18:10:10.488891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9972e204a11'
down_revision: Union[str, Sequence[str], None] = 'df00e40e33f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playerstatistics', sa.Column('saves', sa.Integer(), nullable=True))
    op.add_column('playerstatistics', sa.Column('goals_conceded', sa.Integer(), nullable=True))
    op.add_column('playerstatistics', sa.Column('tackles', sa.Integer(), nullable=True))
    op.add_column('playerstatistics', sa.Column('interceptions', sa.Integer(), nullable=True))
    op.add_column('playerstatistics', sa.Column('clearances', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playerstatistics', 'clearances')
    op.drop_column('playerstatistics', 'interceptions')
    op.drop_column('playerstatistics', 'tackles')
    op.drop_column('playerstatistics', 'goals_conceded')
    op.drop_column('playerstatistics', 'saves')
    # ### end Alembic commands ###
